---
- name: "Perform essentials on all machines"
  hosts: all
  pre_tasks:
    - name: "Perform essentials"
      ansible.builtin.import_tasks: tasks/update.yml
  tags: essentials

- name: "Perform installation of Matrix server"
  ansible.builtin.import_playbook: 'roles/matrix/run.yml'
  tags: matrix


- name: "Perform installation of reverse proxy server"
  hosts: reverse_proxy
  tasks:
    - name: "Import all roles"
      ansible.builtin.include_role:
        name: '{{ reverse_proxy_role }}'
      loop:
        - 'reverseproxy/prepare_machine'
        - 'reverseproxy/haproxy'
#        - 'reverseproxy/nginx'
      loop_control:
        loop_var: reverse_proxy_role
  tags: reverse_proxy

- name: "Perform installation of storage server"
  hosts: storage
  tasks:
    - name: "Import all roles"
      ansible.builtin.include_role:
        name: '{{ storage_role }}'
      loop:
        - 'storage/prepare_machine'
        - 'storage/samba'
      loop_control:
        loop_var: storage_role
  tags: storage
