- name: Create synapse_user in postgres
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: synapse_user
    password: "{{ matrix_synapse_db_password }}" # TODO: create this in-place with ansible

- name: Create synapse database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: synapse
    owner: synapse_user
    encoding: UTF-8
    lc_collate: C
    lc_ctype: C
    template: template0

