- name: "Include all synapse tasks"
  ansible.builtin.include_tasks: "{{ synapse_task }}"
  loop:
    - configure_postgresql.yml
    - install_synapse.yml
    - copy_config_files.yml
  loop_control:
    loop_var: synapse_task
