- name: Restart all mautrix dockers
  community.docker.docker_container:
    restart: true
    name: 'mautrix-{{ item }}'
    image: "dock.mau.dev/mautrix/{{ item }}:latest"
    pull: true
    state: 'started'
    network_mode: host
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/{{ item }}:/data:z"
    restart_policy: unless-stopped
  loop: "{{ mautrix_to_enable }}"

- name: Restart synapse
  become: true
  ansible.builtin.service:
    name: matrix-synapse
    state: restarted
