username: sebsk
timezone: Europe/Warsaw
guid: "1000"
host: "kwasniak.xyz"

packages_reverseproxy:
  - nginx
  - haproxy
  - certbot
  - curl
  - wget

packages_storage:
  - samba

packages_xmpp:
  - sudo
  - nginx
  - socat
  - 'ca-certificates'
  - vim
  - acl
  - prosody
  - luarocks
  - 'liblua5.4-dev'
  - 'curl'
  - 'software-properties-common'
  - 'python3-pip'
  - 'python3-setuptools'
  - 'docker-compose'
  - 'apt-transport-https'
  - 'rsync'


msmtp_accounts:
- account: notifications
  host: "{{ mail_host }}"
  port: "{{ mail_port }}"
  auth: "on"
  from: "{{ mail_notifications }}"
  user: "{{ mail_notifications }}"
  password: "{{ mail_password }}"
msmtp_default_account: "notifications"
msmtp_alias_default: "{{ mail_notifications }}"

lan_network: "{{ '.'.join(ansible_default_ipv4.address.split('.')[0:3]) }}.0/24"
