- name: "Create mautrix facebook folder"
  become: true
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ container_name }}/facebook"
    state: directory
    owner: 1337
    group: 1337
    mode: "0755"
- name: Create facebook.db file
  become: true
  copy:
    content: ""
    dest: "{{ docker_dir }}/{{ container_name }}/facebook/facebook.db"
    force: false
    group: 1337
    owner: 1337
    mode: "0755"

- name: Remove registration if it exists
  become: true
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ container_name }}/facebook/registration.yaml"
    state: absent

- name: Remove config.yaml if it exists
  become: true
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ container_name }}/facebook/config.yaml"
    state: absent

- name: "Copy over facebook.yaml template"
  become: true
  ansible.builtin.template:
    src: 'templates/facebook.yaml.j2'
    dest: "{{ docker_dir }}/{{ container_name }}/facebook/config.yaml"
    owner: 1337
    group: 1337
    mode: "0644"
  notify:
    - Restart mautrix-facebook
    - Restart synapse
