- name: "Create mautrix folders"
  become: true
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ container_name }}/{{ item }}"
    state: directory
    owner: 1337
    group: 1337
    mode: "0755"
  loop: "{{ mautrix_to_enable }}"


- name: Create database files
  become: true
  ansible.builtin.copy:
    content: ""
    dest: "{{ docker_dir }}/{{ container_name }}/{{ item }}/{{ item }}.db"
    force: false
    group: 1337
    owner: 1337
    mode: "0755"
  loop: "{{ mautrix_to_enable }}"

- name: Remove registration if it exists
  become: true
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ container_name }}/{{ item }}/registration.yaml"
    state: absent
  loop: "{{ mautrix_to_enable }}"
  notify:
    - Restart all mautrix dockers
    - Restart synapse

- name: "Copy over mautrix templates"
  become: true
  ansible.builtin.template:
    src: "{{ item }}.yaml.j2"
    dest: "{{ docker_dir }}/{{ container_name }}/{{ item }}/config.yaml"
    owner: 1337
    group: 1337
    mode: "0644"
  loop: "{{ mautrix_to_enable }}"
  notify:
    - Restart all mautrix dockers
    - Restart synapse
