- name: Make sure the mautrix container is created and running
  community.docker.docker_container:
    name: "mautrix-{{ item }}"
    image: "dock.mau.dev/mautrix/{{ item }}:latest"
    pull: true
    state: 'started'
    network_mode: host
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/{{ item }}:/data:z"
    restart_policy: unless-stopped
  loop: "{{ mautrix_to_enable }}"

# docker run --restart unless-stopped -v `pwd`:/data:z dock.mau.dev/mautrix/facebook:<version>
