- name: Make sure the mautrix-facebook container is created and running
  community.docker.docker_container:
    name: 'mautrix-facebook'
    image: "dock.mau.dev/mautrix/facebook:latest"
    pull: true
    state: 'started'
    network_mode: host
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/facebook:/data:z"
    restart_policy: unless-stopped

# docker run --restart unless-stopped -v `pwd`:/data:z dock.mau.dev/mautrix/facebook:<version>
