- name: Restart SSH daemon
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Kill SSH
  ansible.builtin.shell: "sleep 1; pkill -u {{ ansible_ssh_user }} sshd"
  async: 3
  poll: 2
