- name: "Create /opt/docker directory"
  become: true
  ansible.builtin.file:
    path: /opt/docker
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
- name: "Create directory {{ docker_dir }}"
  become: true
  ansible.builtin.file:
    path: "{{ docker_dir }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
