- name: Test nginx
  ansible.builtin.command: nginx -t
  changed_when: false
  register: nginx_validated

- name: "Restart nginx"
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: nginx_validated is succeeded

- name: "First start of Cloudflare IP script"
  ansible.builtin.shell: "/opt/scripts/cloudflare-ips.sh"
