- name: "Include all Matrix machine preparation tasks"
  ansible.builtin.include_tasks: "{{ matrix_machine_preparation_task }}"
  loop:
    - install_packages.yml
    - sudo.yml
  loop_control:
    loop_var: matrix_machine_preparation_task
