- name: Disable SSH password auth
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  notify: Restart SSH daemon

- name: Enable passwordless sudo for "{{ username }}"
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Add the user "{{ username }}" to docker group
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true
  notify: Kill SSH
