- name: "Perform installation of XMPP server"
  hosts: xmpp
  roles:
    - role: 'prepare_machine'
    - { role: 'nginx', become: true }
    - role: 'synapse'
    - role: 'mautrix'
    # - role: 'slidge'

  tags: xmpp
