- name: "Perform installation of Matrix server"
  hosts: matrix
  roles:
    - role: 'prepare_machine'
    - { role: 'nginx', become: true }
    - role: 'synapse'
    - role: 'mautrix'
  tags: matrix
